# serverless-compose.yml
services:
  myApp:
    path: myApp
  apiGateway:
    path: apiGateway
    params:
      commandUrl: ${myApp.functions.commands.domain_name}
      orderUrl: ${myApp.functions.orders.domain_name}
    dependsOn:
      - myApp
