service: apiGateway
configValidationMode: off
provider:
  name: scaleway
  secret:
    SCALEWAY_SECRET_KEY: ${SCW_SECRET_KEY}
    SCALEWAY_DEFAULT_PROJECT_ID: ${SCW_DEFAULT_PROJECT_ID}

plugins:
  - serverless-scaleway-functions

package:
  patterns:
    - '!node_modules/**'
    - '!.gitignore'
    - '!.git/**'
    - '!Makefile'

custom:
  containers:
    kong:
      directory: kong
      minScale: 1
      memoryLimit: 256
      port: 8000
      env:
        FUNCTION_NAMESPACE: myService
